version: "3.4"

volumes:
  my-datavolume:

services:
  db:
    image: mysql
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./dbstorage.sql:/docker-entrypoint-initdb.d/dbstorage.sql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbstorage
    networks:
      - my-network

  api:
    build:
      context: ./StorageApi
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:8080"
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my-network

networks:
  my-network:
